/*
 * Don't edit this file(auto generated by tools)
 */
#ifndef RES_H_
#define RES_H_

#define reIMG__GRP_HEALTH 0x4a43fec8
#define reIMG__HEARTRATE_00000 0x43fb572d
#define reIMG__HEARTRATE_00001 0x43fb572c
#define reIMG__HEARTRATE_00002 0x43fb572f
#define reIMG__HEARTRATE_00003 0x43fb572e
#define reIMG__HEARTRATE_00004 0x43fb5729
#define reIMG__HEARTRATE_00005 0x43fb5728
#define reIMG__HEARTRATE_00006 0x43fb572b
#define reIMG__HEARTRATE_00007 0x43fb572a
#define reIMG__HEARTRATE_00008 0x43fb5725
#define reIMG__HEARTRATE_00009 0x43fb5724

#endif