/*
 * Don't edit this file(auto generated by tools)
 */
#ifndef RES_H_
#define RES_H_

#define reIMG__65 0x375efae5
#define reIMG__66 0x375efae6
#define reIMG__67 0x375efae7
#define reIMG__69 0x375efae9
#define reIMG__70 0x385efc53
#define reIMG__71 0x385efc52
#define reIMG__72 0x385efc51
#define reIMG__APP_PREVIEW 0x6c64d40e
#define reIMG__BACK_0565 0xab1fb194
#define reIMG__FADE_BACK_0565 0x4be990cf
#define reIMG__FADE_HOUR_0_8888 0x18d4bd87
#define reIMG__FADE_HOUR_1_8888 0x21797184
#define reIMG__FADE_HOUR_2_8888 0xc1d44441
#define reIMG__FADE_HOUR_3_8888 0xcafa331e
#define reIMG__FADE_HOUR_4_8888 0x539fb09b
#define reIMG__FADE_HOUR_5_8888 0xf2bd4ed8
#define reIMG__FADE_HOUR_6_8888 0xe6eb0395
#define reIMG__FADE_HOUR_7_8888 0xf81cfd2
#define reIMG__FADE_HOUR_8_8888 0xecc2abdf
#define reIMG__FADE_HOUR_9_8888 0x1696ac9c
#define reIMG__FADE_MIN_0_8888 0x4b96fdaf
#define reIMG__FADE_MIN_1_8888 0x52fe7d2c
#define reIMG__FADE_MIN_2_8888 0xdd39c769
#define reIMG__FADE_MIN_3_8888 0xf16f7a06
#define reIMG__FADE_MIN_4_8888 0x8524bbc3
#define reIMG__FADE_MIN_5_8888 0x1a6fca40
#define reIMG__FADE_MIN_6_8888 0xae8ece3d
#define reIMG__FADE_MIN_7_8888 0x42440ffa
#define reIMG__FADE_MIN_8_8888 0x5679c297
#define reIMG__FADE_MIN_9_8888 0xe0b50cd4
#define reIMG__GRA_0_8888 0xaf9fcade
#define reIMG__GRA_1_8888 0x7a3acb01
#define reIMG__GRA_2_8888 0xd9dff844
#define reIMG__GRA_3_8888 0xd13b4447
#define reIMG__GRA_4_8888 0xc7e85692
#define reIMG__GRA_5_8888 0xcb909b55
#define reIMG__GRA_6_8888 0xd762e698
#define reIMG__GRA_7_8888 0x3845485b
#define reIMG__GRA_8_8888 0x76e82836
#define reIMG__GRA_9_8888 0xe30bd6d9
#define reIMG__GRA_10_8888 0x45ce0515
#define reIMG__GRP_ANI 0x30bc61ec
#define reIMG__GRP_DATE 0xbf0c5d72
#define reIMG__GRP_HOUR 0xa6c1abc0
#define reIMG__GRP_HR 0x3c8afdfc
#define reIMG__GRP_MIN 0xf1da13c2
#define reIMG__GRP_READINESS 0x29d7479a
#define reIMG__GRP_WEEK 0xb7e8d93a
#define reIMG__HEART_8888 0x5fd8b2bd
#define reIMG__PREVIEW_0_0565 0xfbe9a1ec
#define reIMG__PREVIEW_1_0565 0x4e0df5cf
#define reIMG__PREVIEW_2_0565 0xcee94b66
#define reIMG__PREVIEW_3_0565 0xe7f46089
#define reIMG__PREVIEW_4_0565 0xcf3e2a0
#define reIMG__RUN_8888 0x49b9b760

#endif