#include "ids_header.h"

#include <algorithm>
#include <cstdio>

namespace strres {

std::string render_ids_header(const std::vector<StringId>& ids) {
    // Column-align the values by padding names to the longest one.
    std::size_t width = 0;
    for (const auto& id : ids) width = std::max(width, id.name.size());

    std::string out =
        "/* Generated by strpack --ids-header. Do not edit. */\n"
        "/* ResID -> re_name_hash(ResID) namekey. */\n"
        "#ifndef STRING_IDS_H\n"
        "#define STRING_IDS_H\n"
        "\n";

    char hex[16];
    for (const auto& id : ids) {
        std::snprintf(hex, sizeof(hex), "0x%08xu", id.hash);
        out += "#define ";
        out += id.name;
        out.append(width - id.name.size() + 2, ' ');
        out += hex;
        out += '\n';
    }
    out += "\n#endif  /* STRING_IDS_H */\n";
    return out;
}

}  // namespace strres
